name: CI

on:
  push:
    branches:
      - main
      - dev
      - master

  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dbt
        run: pip install dbt-snowflake
        
      - name: Run dbt deps
        run: dbt deps --profiles-dir .

      - name: seed
        with:
          command: "dbt seed --profiles-dir . --full-refresh"

      - name: Run dbt build
        run: dbt build --profiles-dir .

      - name: dbt run
        with:
          command: "dbt run --profiles-dir ."

      - name: Run dbt test
        run: dbt test --profiles-dir .

      - name: generate docs
        with:
          command: "dbt docs generate --profiles-dir ."